# CMake generated Testfile for 
# Source directory: /Users/alex/Documents/development/mogees/mogees-tools/thirdParty/mogees-mlpack/src/mlpack/methods
# Build directory: /Users/alex/Documents/development/mogees/mogees-tools/thirdParty/mogees-mlpack/xcodeproj/src/mlpack/methods
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("preprocess")
subdirs("adaboost")
subdirs("approx_kfn")
subdirs("amf")
subdirs("ann")
subdirs("block_krylov_svd")
subdirs("cf")
subdirs("dbscan")
subdirs("decision_stump")
subdirs("decision_tree")
subdirs("det")
subdirs("emst")
subdirs("fastmks")
subdirs("gmm")
subdirs("hmm")
subdirs("hoeffding_trees")
subdirs("kernel_pca")
subdirs("kmeans")
subdirs("mean_shift")
subdirs("lars")
subdirs("linear_regression")
subdirs("local_coordinate_coding")
subdirs("logistic_regression")
subdirs("lsh")
subdirs("matrix_completion")
subdirs("naive_bayes")
subdirs("nca")
subdirs("neighbor_search")
subdirs("nmf")
subdirs("pca")
subdirs("perceptron")
subdirs("quic_svd")
subdirs("radical")
subdirs("randomized_svd")
subdirs("random_forest")
subdirs("range_search")
subdirs("rann")
subdirs("regularized_svd")
subdirs("softmax_regression")
subdirs("sparse_autoencoder")
subdirs("sparse_coding")
subdirs("nystroem_method")
